name: Refresh Channels
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REFRESH_BRANCH: gha-automated-refresh

jobs:
  refresh-channels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Run refresh script
        run: ./refresh_channels.sh
      - name: Open or refresh PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "do-not-use@elemental.suse.com"
          git config --global user.name "GitHub Action Runner"
          git switch --force-create "${{ env.REFRESH_BRANCH }}" origin/main
          git add .
          
          if git diff-index --quiet HEAD; then
            echo "No new updates. Nothing to do."
            exit 0
          fi
          
          message="Automatic update. Run ID ${{ github.run_id }}, Number ${{ github.run_number}}, Attempt ${{ github.run_attempt }}"
          git commit -m "${message}" 
          git push --force origin "${{ env.REFRESH_BRANCH }}"
          gh pr create --fill --head "${{ env.REFRESH_BRANCH }}" || gh pr edit --title "${message}"
